# Generated by Django 3.1.4 on 2021-03-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=250, null=True, verbose_name='Описание')),
                ('price', models.CharField(choices=[('EU', 'Euro'), ('USD', 'Dollars'), ('UAH', 'Hryvnia'), ('RUB', 'Ruble')], max_length=5, verbose_name='Цена в ')),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Обьявление',
                'verbose_name_plural': 'Обьявления',
                'ordering': ['-data'],
            },
        ),
    ]
