# Generated by Django 3.1.4 on 2021-03-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.CharField(choices=[('Euro', 'EU'), ('Dollars', 'USD'), ('Hryvnia', 'UAH'), ('Ruble', 'RUB')], max_length=10, verbose_name='Цена в '),
        ),
    ]
