# Generated by Django 3.1.4 on 2021-03-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20210319_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='priceSymbol',
            field=models.CharField(choices=[('Euro', 'EU'), ('Dollars', 'USD'), ('Hryvnia', 'UAH'), ('Ruble', 'RUB')], max_length=10, null=True, verbose_name='Цена в '),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
    ]
